# Docker compose 파일 버전(3.8 이상 )
version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: news_letter_db
    restart: always # 컨테이너가 종료되어도 항상 재시작
    # 컨테이너 안에서 PostgreSQL은 5432 포트로 동작함
    # localhost 5433으로 접속하면 컨테이너 내부의 5432로 포스트그리 연결
    # .env에 POSTGRES_PORT 포트 번호가 없으면 기본적으로 5433포트로 외부에서 접속된다.
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      # 데이터 로컬에 영구 보존(컨테이너 삭제해도 데이터 유지)
      # 나의 프로젝트 폴더에 있는 pgdata 폴더에 데이터가 저장된다.
      # pgdata 폴더는 자동으로 생성된다.
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      # 컨테이너 DB가 정상적으로 접속 가능한 상태인지 검사
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - monitoring
  app:
    build: .
    container_name: newsletter-app
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JAVA_OPTS: "-Xms256m -Xmx512m"  # JVM 힙 메모리 제한
    deploy:
      resources:
        limits:
          cpus: '2'    # CPU 2코어로 제한
          memory: 1G   # 전체 메모리 1GB로 제한
        reservations:
          cpus: '0.5'
          memory: 512M
    depends_on:
      postgres:
        condition: service_healthy  # MySQL의 health check가 성공할 때까지 대기
      redis:
        condition: service_started  # Redis가 시작되면 바로 시작
    networks:
      - monitoring

  # 데이터 수집
  # 스프링부트의 데이터를 추출하는 역할
  prometheus:
    image: prom/prometheus
    container_name: prometheus_newsletter
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  # 데이터 시각화
  # 대시보드 - 데이
  grafana:
    image: grafana/grafana
    container_name: grafana_newsletter
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Redis
  redis:
    image: redis:7.0
    container_name: redis-server_newsletter
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  # Redis Exporter
  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter_newsletter
    ports:
      - "9121:9121"
    command:
      - '--redis.addr=redis://redis:6379'
    depends_on:
      - redis
    networks:
      - monitoring


volumes:
  mysql_data:
  grafana_data:
  redis_data:

networks:
  monitoring: